"""GST filing calendar — deterministic date arithmetic, no LLM, no external API."""
from datetime import date

from fastapi import APIRouter

from core.classify import ITC_DEADLINES, get_fy_start

router = APIRouter()


@router.get("/api/gst/calendar")
def gst_calendar():
    today = date.today()

    # GSTR-3B: due 20th of each month (for most taxpayers)
    if today.day <= 20:
        gstr3b_deadline = date(today.year, today.month, 20)
    elif today.month == 12:
        gstr3b_deadline = date(today.year + 1, 1, 20)
    else:
        gstr3b_deadline = date(today.year, today.month + 1, 20)

    # GSTR-2B: generated by GSTN on the 14th of each month
    if today.day < 14:
        gstr2b_available = date(today.year, today.month, 14)
    elif today.month == 12:
        gstr2b_available = date(today.year + 1, 1, 14)
    else:
        gstr2b_available = date(today.year, today.month + 1, 14)

    current_fy = get_fy_start(today)
    prev_fy_deadline = ITC_DEADLINES.get(current_fy - 1)
    itc_window_status = "CLOSED" if prev_fy_deadline and today > prev_fy_deadline else "OPEN"

    return {
        "today": today.isoformat(),
        "gstr3b_deadline": gstr3b_deadline.isoformat(),
        "gstr3b_days_remaining": (gstr3b_deadline - today).days,
        "gstr2b_available": gstr2b_available.isoformat(),
        "gstr2b_days_until": (gstr2b_available - today).days,
        "itc_window_fy2024_25": itc_window_status,
        "itc_deadline_date": prev_fy_deadline.isoformat() if prev_fy_deadline else None,
    }
